apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pokedex
  description: The pokedex API
  tags: 
    - pokedex
    - openapi
    - poketeam
  links:
    - url: http://localhost:5000/pokemon
  annotations:
    backstage.io/managed-by-location: url:https://github.com/dan-gaskin/dg-backstage-api-test/blob/main/catalog-info.yml
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/dan-gaskin/dg-backstage-api-test
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  system: pokedex
  definition:
    $text: ./docs/swagger.json
  providesApis:
    - pokemon/{pokemonName}
    - pokemon/translated/{pokemonName}
  consumesApis:
    - https://pokeapi.co/api/v2/pokemon-species/{pokemonName}
    - https://api.funtranslations.com/translate/yoda
    - https://api.funtranslations.com/translate/shakespeare