apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pokedex
  description: pokedex product
  tags: 
    - pokedex
    - openapi
    - poketeam
  links:
    - url: http://localhost:5000/pokemon
      title: api endpoint
    - url: https://grafana.com
      title: grafana dashboard
  annotations:
    backstage.io/managed-by-location: url:https://github.com/dan-gaskin/dg-backstage-api-test/blob/main/catalog-info.yml
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: dan-gaskin/dg-backstage-api-test
    circleci.com/project-slug: github/dan-gaskin/dg-backstage-api-test
    backstage.io/code-coverage: scm-only
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: pokedex
  providesApis:
    - pokedex-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pokedex-api
  description: The pokedex API
  tags: 
    - pokedex
    - openapi
    - poketeam
  links:
    - url: http://localhost:5000/pokemon
  annotations:
    backstage.io/managed-by-location: url:https://github.com/dan-gaskin/dg-backstage-api-test/blob/main/catalog-info.yml
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/dan-gaskin/dg-backstage-api-test
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  system: pokedex
  definition:
    $text: ./docs/swagger.json