apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pokedex
  description: The pokedex API
  tags: 
    - pokedex
    - openapi
    - team a
  links:
    url: http://localhost:5000
  annotations:
    backstage.io/managed-by-location: url:https://github.com/dan-gaskin/dg-backstage-api-test/blob/main/api/catalog-info.yml
    backstage.io/techdocs-ref: ./docs
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: ./docs/swagger.json 